# Generated by Django 3.2.9 on 2023-04-09 12:00

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=todo_app.models.one_week_hence),
        ),
    ]
