# Generated by Django 3.2.9 on 2023-04-10 18:43

from django.conf import settings
from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0005_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(todo_app.models.get_superuser), related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
